# Generated by Django 5.1.5 on 2025-04-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField(blank=True)),
                ('price', models.TextField(blank=True)),
                ('storetype', models.TextField(default='Local')),
                ('storelocation', models.TextField(blank=True)),
                ('storename', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField(blank=True)),
                ('price', models.TextField(blank=True)),
                ('storetype', models.TextField(default='Online')),
                ('websitelink', models.TextField(blank=True)),
                ('storename', models.TextField(blank=True)),
            ],
        ),
    ]
