# Generated by Django 5.1.5 on 2025-04-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProductApi', '0003_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
