# Generated by Django 5.1.5 on 2025-04-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProductApi', '0004_productreview_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
